<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-SQL-Journey/blob/main/Day03_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display only the first_name column from employees
pd.read_sql("""
SELECT first_name
FROM employees;
""", conn)

   first_name
0       Aarav
1      Vivaan
2      Aditya
3        Riya
4       Priya
5        Neha
6       Rahul
7        Amit
8        John
9        Emma
10       Noah
11     Olivia
12       Liam
13     Sophia
14     Ananya
15      Karan
16      Rohan
17      Sneha
18      David
19       Sara
20      Arjun
21       Isha
22      Kabir
23      Meera
24     Vikram
25      Nisha
26     Daniel
27      Grace
28      Aryan
29      Pooja

In [ ]:
#Display department_name from department
pd.read_sql("""
SELECT department_name
FROM departments;
""", conn)

    department_name
0                HR
1           Finance
2                IT
3         Marketing
4             Sales
5        Operations
6           Support
7             Legal
8  Data Engineering
9          Security

In [ ]:
#Display product_name and price from products
pd.read_sql("""
SELECT product_name, price
FROM products;
""", conn)

          product_name    price
0       Laptop Model 1  90499.0
1       Laptop Model 2  90999.0
2       Laptop Model 3  91499.0
3       Laptop Model 4  91999.0
4       Mobile Model 1  30499.0
5       Mobile Model 2  30999.0
6       Mobile Model 3  31499.0
7       Mobile Model 4  31999.0
8   Headphones Model 1   5499.0
9   Headphones Model 2   5999.0
10  Headphones Model 3   6499.0
11  Headphones Model 4   6999.0
12     Monitor Model 1  16499.0
13     Monitor Model 2  16999.0
14     Monitor Model 3  17499.0
15     Monitor Model 4  17999.0
16    Keyboard Model 1   2499.0
17    Keyboard Model 2   2999.0
18    Keyboard Model 3   3499.0
19    Keyboard Model 4   3999.0
20       Mouse Model 1   1499.0
21       Mouse Model 2   1999.0
22       Mouse Model 3   2499.0
23       Mouse Model 4   2999.0
24      Camera Model 1  46499.0

In [ ]:
#Display customer_name and city from customers
pd.read_sql("SELECT * FROM customers LIMIT 5;", conn)

   customer_id first_name last_name             email       phone       city
0            1      Akash    Sharma   akash1@mail.com  9666696518  Bangalore
1            2       Ritu       Das    ritu2@mail.com  9627404182  Bangalore
2            3      Mohit     Kumar   mohit3@mail.com  9208428912     Mumbai
3            4     Simran       Das  simran4@mail.com  9979444461    Chennai
4            5       Yash    Sharma    yash5@mail.com  9426111115       Pune

In [ ]:
#Display employee_id , first name and salary from employees
pd.read_sql("""
SELECT employee_id, first_name, salary
FROM employees;
""", conn)

    employee_id first_name    salary
0             1      Aarav   47500.0
1             2     Vivaan  105000.0
2             3     Aditya   45000.0
3             4       Riya  117500.0
4             5      Priya  120000.0
5             6       Neha   67500.0
6             7      Rahul   90000.0
7             8       Amit  105000.0
8             9       John   45000.0
9            10       Emma   97500.0
10           11       Noah  112500.0
11           12     Olivia   50000.0
12           13       Liam  105000.0
13           14     Sophia   97500.0
14           15     Ananya   72500.0
15           16      Karan  117500.0
16           17      Rohan   52500.0
17           18      Sneha   50000.0
18           19      David   62500.0
19           20       Sara   85000.0
20           21      Arjun   42500.0
21           22       Isha   60000.0
22           23      Kabir  105000.0
23           24      Meera  112500.0
24           25     Vikram   57500.0
25           26      Nisha  110000.0
26           27     Daniel   60000.0
27           28      Grace   40000.0
28           29      Aryan   70000.0
29           30      Pooja  120000.0

In [ ]:
#Display order_id , customer_id and order_date from orders
Display